version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "9988:9988"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - HOST=0.0.0.0
      - PORT=9988
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9988/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "13145:13145"
    environment:
      - PORT=13145
      - HOSTNAME=0.0.0.0
      - NODE_ENV=production
      - BACKEND_URL=http://backend:9988
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:13145/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
